{{- if and (eq .Values.server.config.authenticationType "PASSWORD") (.Values.auth.passwordAuth) }}
apiVersion: v1
kind: Secret
metadata:
  name: trino-password-authentication
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}
